spring:
  profiles:
    active: dev

#公共配置
  # 这个开发配置为false，避免改了模板还要重启服务器
  thymeleaf: cache=false
  # 这个是配置模板路径的，默认就是templates，可不用配置
  prefix: classpath:/templates/
  # 这个可以不配置，检查模板位置
  check-template-location: true
  # 下面3个不做解释了，可以不配置
  suffix: html
  encoding:
    charset: UTF-8
  ervlet.content-type: text/html
  # 模板的模式
  mode: HTML5
  messages:
    encoding: UTF-8
  banner:
    charset: UTF-8
server:
  tomcat:
    uri-encoding: UTF-8

#高德web服务KEY 个人开发者，6000/日
gaodeKey: 9fcf751615d582aaf4d884e8ed11f3bb
#高德地图地理编码 API 服务地址 get json
geocodeUrl: https://restapi.amap.com/v3/geocode/geo?key={key}&address={address}
#高德地图逆地理编码 API 服务地址 get json
#regeocodeUrl: https://restapi.amap.com/v3/geocode/geo